export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_EXISTING_PRODUCT = 'INCREASE_EXISTING_PRODUCT';
export const DECREASE_EXISTING_PRODUCT = 'DECREASE_EXISTING_PRODUCT';
